php_version: 5
global_exclude_dirs:
    - vendor
    - vendors
    - var

rules:
    php.use_deprecated_function:
        enabled: false
    third_party.use_deprecated_class:
        enabled: false
    third_party.use_deprecated_service:
        enabled: false
