<?php

namespace AppBundle\Repository;

/**
 * EducationalReferentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationalReferentRepository extends \Doctrine\ORM\EntityRepository
{
}
