<?php

namespace AppBundle\Repository;

/**
 * ObtentionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObtentionRepository extends \Doctrine\ORM\EntityRepository
{
}
