<?php

namespace AppBundle\Repository;

/**
 * ProfesionnalReferentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionnalReferentRepository extends \Doctrine\ORM\EntityRepository
{
}
