<?php

namespace AppBundle\Repository;

/**
 * promoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoteRepository extends \Doctrine\ORM\EntityRepository
{
}
