parameters:
    project_title: symfony_project
    project_name: symfony_project
    project_url: symfony_project.dev
    developer_email: "%smart_developper_email%"
    contact_email: "%smart_contact_email%"
    email_sender_name: symfony_project
    vagrant_ip: 192.168.9.11
    vagrant_db_password: 1234
    smart.host_env: dev
    smart.project_domain: symfony_project.dev
    smart.project_name: symfony_project
    smart.project_title: symfony_project
